### ISSUE TITLE
Ground truth

### ISSUE THREAD

**Issue by albertus-andito** [northeastern-datalab/alite-new#1]
Hi, is the ground truth label not included in the benchmarks? Thanks

**Comment by aamodkh** [comment]
Hi, in each integration set, the columns having the same column headers are the matching columns. Since we do not rely on column headers and only use column values, the column headers are hand-annotated to represent the ground truth. Therefore, we do not have a separate ground truth label file.

**Comment by aamodkh** [comment]
Hi, in each integration set, the columns having the same column headers are the matching columns. Since we do not rely on column headers and only use column values, the column headers are hand-annotated to represent the ground truth. Therefore, we do not have a separate ground truth label file.

**Comment by albertus-andito** [comment]
Ah I see, thank you!

**Comment by albertus-andito** [comment]
Apologies for reopening this old issue.

What about the Real dataset? Aren't they supposed to have different column headers, which is why you could evaluate schema-based matching methods like COMA on it?

**Comment by aamodkh** [comment]
Hi Albertus,

Please find the column headers for Real Benchmark 
[here](statistics/real_benchmark_schemas.csv).

The file contains the real column headers (column_header) for each column in the benchmark and also their ground truth annotation (groundtruth_header). The columns having the same ground truth annotations are the matching columns. The columns could have nan or unnamed as column headers, they are the columns having missing headers, or column headers that were not loaded to data frame due to bad formatting.

**Comment by aamodkh** [comment]
Hi Albertus,

Please find the column headers for Real Benchmark 
[here](https://github.com/northeastern-datalab/alite/blob/main/statistics/real_benchmark_schemas.csv).

The file contains the real column headers (column_header) for each column in the benchmark and also their ground truth annotation (groundtruth_header). The columns having the same ground truth annotations are the matching columns. The columns could have nan or unnamed as column headers, they are the columns having missing headers, or column headers that were not loaded to data frame due to bad formatting.

**Comment by albertus-andito** [comment]
Thank you for responding so swiftly!
